# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Students_pb2 as Students__pb2


class StudentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStudentInfo = channel.unary_unary(
        '/StudentService/GetStudentInfo',
        request_serializer=Students__pb2.StudentRequest.SerializeToString,
        response_deserializer=Students__pb2.StudentResponse.FromString,
        )


class StudentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStudentInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStudentInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetStudentInfo,
          request_deserializer=Students__pb2.StudentRequest.FromString,
          response_serializer=Students__pb2.StudentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'StudentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
