# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Students.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Students.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eStudents.proto\"\'\n\x0eStudentRequest\x12\x15\n\rstudentNumber\x18\x01 \x01(\t\"E\n\x0fStudentResponse\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\r\n\x05major\x18\x03 \x01(\t2E\n\x0eStudentService\x12\x33\n\x0eGetStudentInfo\x12\x0f.StudentRequest\x1a\x10.StudentResponseb\x06proto3')
)




_STUDENTREQUEST = _descriptor.Descriptor(
  name='StudentRequest',
  full_name='StudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentNumber', full_name='StudentRequest.studentNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=57,
)


_STUDENTRESPONSE = _descriptor.Descriptor(
  name='StudentResponse',
  full_name='StudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='StudentResponse.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='StudentResponse.lastName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='major', full_name='StudentResponse.major', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['StudentRequest'] = _STUDENTREQUEST
DESCRIPTOR.message_types_by_name['StudentResponse'] = _STUDENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StudentRequest = _reflection.GeneratedProtocolMessageType('StudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTREQUEST,
  '__module__' : 'Students_pb2'
  # @@protoc_insertion_point(class_scope:StudentRequest)
  })
_sym_db.RegisterMessage(StudentRequest)

StudentResponse = _reflection.GeneratedProtocolMessageType('StudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTRESPONSE,
  '__module__' : 'Students_pb2'
  # @@protoc_insertion_point(class_scope:StudentResponse)
  })
_sym_db.RegisterMessage(StudentResponse)



_STUDENTSERVICE = _descriptor.ServiceDescriptor(
  name='StudentService',
  full_name='StudentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStudentInfo',
    full_name='StudentService.GetStudentInfo',
    index=0,
    containing_service=None,
    input_type=_STUDENTREQUEST,
    output_type=_STUDENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STUDENTSERVICE)

DESCRIPTOR.services_by_name['StudentService'] = _STUDENTSERVICE

# @@protoc_insertion_point(module_scope)
